### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by vibrantabhi19** [vibrantabhi19/vibrantabhi19.github.io#1]
The search is not working for now, probably the links are not properly referred. See the code and explore.
I am using Super search so you can go to its official repo to get help. https://github.com/chinchang/super-search.

**Comment by tanayag** [comment]
search is working right,
check it again :+1:

**Comment by vibrantabhi19** [comment]
No body volunteered for this so I fixed it myself.
Appreciate your comment @tanayag
