### ISSUE TITLE
Add/modify search box

### ISSUE THREAD

**Issue by vibrantabhi19** [vibrantabhi19/vibrantabhi19.github.io#10]
The search is not working in the navbar. You can either work on it to make it work or add an new search bar. 
The following link is very easy to implement.
https://github.com/chinchang/super-search

**Comment by babhishek21** [comment]
Which one do you prefer? Fixing the sidebar search already available, or adding in `super-search`?

**Comment by vibrantabhi19** [comment]
@babhishek21 I am open for both. 
Whichever you feel is can be incubated easily. Totally your choice

**Comment by babhishek21** [comment]
@vibrantabhi19 Do you mind assigning this to me? Thanks!

**Comment by vibrantabhi19** [comment]
Sure, doing it :)
Thanks for your interest @babhishek21 Really appreciate it.

**Comment by vibrantabhi19** [comment]
![screenshot from 2016-10-14 23-14-48](https://cloud.githubusercontent.com/assets/6832471/19397159/453ded4c-9264-11e6-8520-8ac5cc2572d6.png)
I am unable to assign you. You can go through with your PR, nobody else is assigned so I guess that wont be an issue

**Comment by babhishek21** [comment]
Yes. [Assigning](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) is limited to yourself, collaborators and members of an organisation. No problem!

**Comment by vibrantabhi19** [comment]
I tried assigning someone to one of the closed Issues and I was successful in doing so.
Refer to https://github.com/vibrantabhi19/vibrantabhi19.github.io/issues/9
Anyways, go for the PR :)

**Comment by babhishek21** [comment]
@vibrantabhi19 Added a PR. Do take a look at it.
