### ISSUE TITLE
Add responsive Navbar Toggle/Button for smaller screen

### ISSUE THREAD

**Issue by vibrantabhi19** [vibrantabhi19/vibrantabhi19.github.io#3]
When opened on smaller screen the Navigation part is not properly oriented. What may look best is to have a toggle/button for navigation at the top right corner of the screen
I am attaching the scrrenshot of how the template behave on smaller screen.
![screenshot_2016-10-08-22-38-06-361](https://cloud.githubusercontent.com/assets/6832471/19214737/0cbafec6-8da8-11e6-8ed6-821c6c0956f3.jpeg)
Volunteer yourself or comment to discuss further

**Comment by vedsarkushwaha** [comment]
Hey,

I ready to take this up. Have some experience of responsive pages.
I'm new to "hacktoberfest.digitalocean.com". From here I got this issue link.

**Comment by vibrantabhi19** [comment]
Go on, have a look.
If you wanna set this theme locally then you have to install gem and locally host it.
-You need to have ruby installed in your system.
-Install bundler which helps in specifying and installing dependencies of any Ruby project. gem install bundler
-Go to the root of the repo and run this - bundle install
-Then - bundle exec jekyll serve
Or follow the official docs at https://jekyllrb.com/docs/home/

Really appreciate your interest in Open source, Happy coding :)
